### PR TITLE
Moar 4.2 states initialization fixes

### PR DESCRIPTION
**Pull request by huoxito**
These changes depend on https://github.com/state-machines/state_machines/pull/3 getting merged and having a new gem release out.

### CODE REVIEW

**Comment by seuros** [comment]
Failed in 4.1 :/

**Comment by huoxito** [comment]
ops haha @seuros I'll take a look later, also need to double check spree builds again and sm-activemodel as well

**Comment by huoxito** [comment]
should be good on 4.1 now too o/

**Comment by JDutil** [comment]
:+1: Nice thanks @huoxito

**Comment by seuros** [comment]
LGTM.
@huoxito , @JDutil , i think i can build a meta repo with all the code in it (core+integrations), wdyt ?

**Comment by JDutil** [comment]
That would probably make life simpler than switching back and forth between many projects.

**Comment by JDutil** [comment]
Could you cut a stable gem release please?

**Comment by seuros** [comment]
yes

**Comment by seuros** [comment]
released 0.1.0

**Comment by JDutil** [comment]
Thanks! :shipit:

**Pull request merged**
