### PR TITLE
Respect use_transactions configuration.

### PR DESCRIPTION
**Pull request by rosskevin**
This depends on `state_machines` pull request https://github.com/state-machines/state_machines/pull/17

Please see commit comments.  Aligned test assertions with documentation, former assertions were different than documentation.

### CODE REVIEW

**Comment by rosskevin** [comment]
`Gemfile` needs to be reverted once the pull in the main project is accepted.

**Comment by rosskevin** [comment]
Resolves #16

**Comment by seuros** [comment]
Do we have this issue with the other extensions ? Activemodel for example.

**Comment by rosskevin** [comment]
I doubt there is a problem with activemodel since this project uses it as a dependency.  There were ultimately very few changes in this project, though the behavior assertions should be scrutinized.  I think the behavior changes are as you would expect them to be, and unlikely to cause pain.

I think the parent project that was already merged could _possibly_ cause a test failure due to changes in options, but those options are asserted in the codebase.

**Comment by rosskevin** [comment]
The transitive dependency `state_machines-activemodel` is currently too restrictive with the dependency on `'state_machines', '~> 0.2.0'`.  I'll submit a pull for `>=`

**Comment by rosskevin** [comment]
Depends on https://github.com/state-machines/state_machines-activemodel/pull/1

**Comment by rosskevin** [comment]
My squashing skills leave a bit to be desired. Still working on it.

**Comment by rosskevin** [comment]
I had to submit a different pull that was clean.  I reverted my test change/gemfile changes and submitted #18.

**Pull request closed without merging**
